In [2]:
#Import Libraries:
#Start by importing the necessary libraries.
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import *

In [3]:
#Load the Iris Dataset:
#Load the Iris dataset from scikit-learn.
iris_data = load_iris()
iris      = pd.DataFrame(data = iris_data.data, columns = iris_data.feature_names)
iris['target'] = iris_data.target
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [4]:
#Check whether the dataset contains null values. Here, dataset has no null values.
iris.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [5]:
#Attempting to set up the feature matrix X and the target variable y based on the Iris dataset.
X = iris.drop("target",axis=1)
y = iris["target"]

In [7]:
#First split the Data:
#Split the dataset into training and testing sets.
#Then create and Train the Random Forest Model:
#Create a Random Forest Classifier and train it on the training data.
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
rfc = RandomForestClassifier(n_estimators=100,random_state=42)
rfc.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [8]:
#Create and Train the Random Forest Model:
#Create a Random Forest Classifier and train it on the training data.
#Here, n_estimators is the number of trees in the forest. You can adjust it based on your requirements.
y_pred = rfc.predict(X_test)
np.array(y_pred)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [9]:
#calculate the confusion matrix, accuracy score, R-squared score, and
#classification report using some predictions (y_pred) and true labels
#(y_test)
cfm = confusion_matrix(y_test,y_pred)
asc = accuracy_score(y_test,y_pred)
r2s = r2_score(y_test,y_pred)
cre = classification_report(y_test,y_pred)

In [10]:
print(f"Confusion matrix is:\n{cfm}")

Confusion matrix is:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [11]:
asc

1.0

In [12]:
r2s

1.0

In [13]:
print("classification_report:\t\n",cre)

classification_report:	
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

